apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: dotcms
  name: dotcms
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8081
  - name: "8443"
    port: 8443
    targetPort: 8082
  selector:
    io.kompose.service: dotcms
status:
  loadBalancer: {}
